// One-time migration generated by prepare-normalization.py. Run before the domain reload.
var manifest=Newtonsoft.Json.Linq.JObject.Parse(System.IO.File.ReadAllText("Builds/Normalization/manifest.json"));
void Folder(string path) {
    if(UnityEditor.AssetDatabase.IsValidFolder(path))return;
    string parent=System.IO.Path.GetDirectoryName(path).Replace('\\','/');Folder(parent);
    UnityEditor.AssetDatabase.CreateFolder(parent,System.IO.Path.GetFileName(path));
}
var completed=new System.Collections.Generic.List<string>();
UnityEditor.EditorApplication.LockReloadAssemblies();
UnityEditor.AssetDatabase.DisallowAutoRefresh();
try {
    foreach(var entry in manifest["Moves"]) {
        string from=(string)entry["From"],to=(string)entry["To"];
        if(string.IsNullOrEmpty(UnityEditor.AssetDatabase.AssetPathToGUID(from)) && !string.IsNullOrEmpty(UnityEditor.AssetDatabase.AssetPathToGUID(to))) { completed.Add(from+" -> "+to);continue; }
        Folder(System.IO.Path.GetDirectoryName(to).Replace('\\','/'));
        string error=UnityEditor.AssetDatabase.MoveAsset(from,to);
        if(!string.IsNullOrEmpty(error))throw new System.Exception(from+" -> "+to+": "+error);
        completed.Add(from+" -> "+to);
    }
    UnityEditor.AssetDatabase.StartAssetEditing();
    try {
        foreach(var entry in manifest["Rewrites"])
            System.IO.File.WriteAllText((string)entry["Path"],System.IO.File.ReadAllText((string)entry["Source"]),new System.Text.UTF8Encoding(false));
    } finally { UnityEditor.AssetDatabase.StopAssetEditing(); }
} finally {
    System.IO.File.WriteAllLines("Builds/Normalization/completed-moves.txt",completed);
    UnityEditor.AssetDatabase.AllowAutoRefresh();
    UnityEditor.EditorApplication.UnlockReloadAssemblies();
}
UnityEditor.AssetDatabase.Refresh();
return new {Moved=completed.Count,Rewritten=manifest["Rewrites"].Count()};
